[package]
name = "spring"
version = "0.1.0"
authors = ["kEDIT <kesh.bhamidipaty@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.22.0"
structopt = "0.2.18"